import fs from "fs";
import path from "path";
import { dump } from "js-yaml";
import { swaggerSpec } from "../config/swaggerConfig.js";

// Enterprise OpenAPI / Swagger / SDK Generation Standard (Enterprise
// Architecture Hardening Phase, Improvement 15). "Versioned Documentation
// — v1 Docs -> v2 Docs -> v3 Docs. Never overwrite old documentation."
// Writes the CURRENT live `swaggerSpec` (the same object `/openapi.json`,
// `/openapi.yaml`, and `/api-docs` all serve at runtime — one real source,
// never a hand-maintained second copy) as a frozen, versioned snapshot
// under docs/openapi/, and — when `openapi-typescript` is installed —
// generates real TypeScript SDK types from it under docs/sdk/typescript/.
// Run via `npm run generate:openapi` before cutting a release, per this
// standard's own "Documentation Governance: Before Release" rule.

const repoRoot = path.resolve(import.meta.dirname, "..");
const openApiDir = path.join(repoRoot, "docs", "openapi");
const sdkDir = path.join(repoRoot, "docs", "sdk", "typescript");

const currentVersion = `v${swaggerSpec.info.version.split(".")[0]}`;

fs.mkdirSync(openApiDir, { recursive: true });
fs.mkdirSync(path.join(openApiDir, "common"), { recursive: true });

const jsonPath = path.join(openApiDir, `${currentVersion}.json`);
const yamlPath = path.join(openApiDir, `${currentVersion}.yaml`);
fs.writeFileSync(jsonPath, JSON.stringify(swaggerSpec, null, 2));
fs.writeFileSync(yamlPath, dump(swaggerSpec));
console.log(`Wrote ${path.relative(repoRoot, jsonPath)} and ${path.relative(repoRoot, yamlPath)} (${Object.keys(swaggerSpec.paths).length} paths, ${Object.keys(swaggerSpec.components.schemas).length} schema components).`);

try {
  const { default: openapiTS, astToString } = await import("openapi-typescript");
  const ast = await openapiTS(swaggerSpec);
  const output = astToString(ast);

  fs.mkdirSync(sdkDir, { recursive: true });
  const sdkPath = path.join(sdkDir, "index.d.ts");
  fs.writeFileSync(sdkPath, `// AUTO-GENERATED by scripts/generateOpenApiArtifacts.js from docs/openapi/${currentVersion}.json — do not hand-edit.\n\n${output}`);
  console.log(`Wrote ${path.relative(repoRoot, sdkPath)} (real TypeScript types generated from the live OpenAPI spec via openapi-typescript).`);
} catch (err) {
  console.warn(`TypeScript SDK generation skipped — openapi-typescript unavailable or failed: ${err.message}`);
}
