import mongoose from "mongoose";

// Enterprise Financial Dashboard — Finance Module Part 25. "Alerts: Low
// Cash, High Expenses, Large Payment, Overdue Receivable, Overdue
// Payable, Budget Exceeded, Negative Cash Flow, Tax Due, Custom Alerts."
// A real, persisted, acknowledgeable record — generated by
// `KPIEngine.refreshFinanceSummary` whenever a real metric crosses a
// real configured threshold, never fabricated. Tenant-scoped only — no
// branchId.
const DashboardAlertSchema = new mongoose.Schema({
  tenantId: { type: String, required: true, index: true },
  // Config-driven (dashboardAlertTypes) — LowCash, HighExpenses,
  // LargePayment, OverdueReceivable, OverduePayable, BudgetExceeded,
  // NegativeCashFlow, TaxDue, Custom.
  alertType: { type: String, required: true, index: true },
  // Config-driven (dashboardAlertSeverities) — Info, Warning, Critical.
  severity: { type: String, required: true },
  message: { type: String, required: true },
  value: { type: Number, default: null },
  threshold: { type: Number, default: null },
  // Polymorphic link to whatever real record triggered this (a specific
  // Payment for LargePayment, a Receivable for OverdueReceivable, ...) —
  // same no-`ref` discipline as PaymentModel.allocations' own
  // targetType/targetId.
  sourceType: { type: String, default: null },
  sourceId: { type: mongoose.Schema.Types.ObjectId, default: null },
  // Active | Acknowledged | Resolved.
  status: { type: String, required: true, default: "Active" },
  acknowledgedBy: { type: String, default: null },
  acknowledgedAt: { type: Date, default: null },
  triggeredAt: { type: Date, default: Date.now }
}, { timestamps: true });

DashboardAlertSchema.index({ tenantId: 1, status: 1, triggeredAt: -1 });
DashboardAlertSchema.index({ tenantId: 1, alertType: 1, status: 1 });

DashboardAlertSchema.set("toJSON", {
  transform: (_, ret) => {
    delete ret.__v;
    return ret;
  }
});

const DashboardAlertModel = mongoose.model("dashboard_alert", DashboardAlertSchema);

export default DashboardAlertModel;
