import mongoose from "mongoose";

// Supplier Self-Service Portal (PRD "CRM Feature Map by Phase" Phase 3
// module 24) — a supplier's own submitted claim for payment, distinct
// from VendorPaymentModel (the agency's own, internally-created payment
// RUN against a vendor). A VendorInvoice is the inbound document a
// supplier submits for staff review; once approved, staff create the
// actual VendorPaymentModel payment through the existing, unrelated
// vendor-payment workflow (VendorPaymentService) — this model
// deliberately does not auto-create one, since that workflow already has
// its own approval/scheduling/execution steps this shouldn't bypass.
const VendorInvoiceSchema = new mongoose.Schema({
  tenantId: {
    type: String,
    required: true,
    index: true
  },
  vendorId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "vendor",
    required: true,
    index: true
  },
  // The supplier's own reference number on their invoice — never
  // generated by this system (contrast with e.g. InvoiceModel.invoiceNumber,
  // which this agency generates itself for its own outbound invoices).
  supplierInvoiceNumber: { type: String, required: true, trim: true },
  amount: { type: Number, required: true, min: 0 },
  currency: { type: String, required: true, uppercase: true },
  description: { type: String, default: null },
  attachments: { type: [String], default: [] },
  status: {
    type: String,
    enum: ["Submitted", "UnderReview", "Approved", "Rejected"],
    default: "Submitted",
    index: true
  },
  reviewedBy: { type: String, default: null },
  reviewedAt: { type: Date, default: null },
  reviewNotes: { type: String, default: null }
}, { timestamps: true });

VendorInvoiceSchema.index({ tenantId: 1, vendorId: 1, status: 1 });
VendorInvoiceSchema.index({ tenantId: 1, createdAt: -1 });

VendorInvoiceSchema.set("toJSON", {
  transform: (_, ret) => {
    delete ret.__v;
    return ret;
  }
});

const VendorInvoiceModel = mongoose.model("vendor_invoice", VendorInvoiceSchema);

export default VendorInvoiceModel;
